config/routes.rb
Rails.application.routes.draw do

  namespace :cct_vast_db do
    resources :cameras do
      collection do

        put  :create
        patch :update
        patch :update_soc

        post :import
        get  :create_database_index
        get  :show_cam_info
        get  :show_cam_info_index
        get  :show_soc_info
        get  :show_soc_info_index

        get  :new_and_update_cam_info_index
        get  :new_cam_info_index
        post  :new_cam_info_index

        patch :new_cam_info

        post :update_cam_info_index
        get  :update_cam_info_index
        patch  :update_success
        get  :update_cam_info

        post :test_update
        patch :test_update

        get  :update_cam_other_info_index
        get  :update_cam_other_info

        post :create_camera_other_info

        get  :export_csv_index

      end
    end
  end

  namespace :cct_vast_db do
    resources :camera_other_infos do
      collection do
        post :import
        get  :import_success
        get  :import_fail
      end
    end
  end

  namespace :cct_vast_db do
    resources :test_soc_cameras do
      collection do
        post :import
        get  :import_success
      end
    end
  end

  namespace :cct_vast_db do
    resources :show_cam_info_and_updates do
      collection do
        post  :import
        get   :import_success
      end
    end
  end

  namespace :cct_nvr_db do
    resources :cameras do
      collection do

        put  :create
        patch :update
        patch :update_soc

        post :import
        get  :create_database_index
        get  :show_cam_info
        get  :show_cam_info_index
        get  :show_soc_info
        get  :show_soc_info_index

        get  :new_and_update_cam_info_index
        get  :new_cam_info_index
        post  :new_cam_info_index

        patch :new_cam_info

        post :update_cam_info_index
        get  :update_cam_info_index
        patch  :update_success
        get  :update_cam_info

        post :test_update
        patch :test_update

        get  :update_cam_other_info_index
        get  :update_cam_other_info

        post :create_camera_other_info

        get  :export_csv_index

      end
    end
  end

  namespace :cct_nvr_db do
    resources :camera_other_infos do
      collection do
        post :import
        get  :import_success
        get  :import_fail
      end
    end
  end

  namespace :cct_nvr_db do
    resources :test_soc_cameras do
      collection do
        post :import
        get  :import_success
      end
    end

  end

  namespace :cct_nvr_db do
    resources :show_cam_info_and_updates do
      collection do
        post  :import
        get   :import_success
      end
    end
  end

  get 'welcome/test_index/index' => 'welcome/test_index#index'

  root to: "welcome/index#index"

end

app/controllers/welcome/index_controller.rb
class Welcome::IndexController < ApplicationController
end

app/controllers/welcome/test_index_controller.rb
class Welcome::TestIndexController < ApplicationController
end

app/helpers/welcome/index_helper.rb
module Welcome::IndexHelper
end

app/helpers/welcome/test_index_helper.rb
module Welcome::TestIndexHelper
end

app/views/welcome/index/index.erb
<!DOCTYPE html>
<html>


  <head>
    <title>VAST Device Pack資料庫</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative CSS3 Animation Menus" />
    <meta name="keywords" content="menu, navigation, animation, transition, transform, rotate, css3, web design, component, icon, slide" />
    <meta name="author" content="Codrops" />
    <link rel="shortcut icon" href="../favicon.ico">
    <link rel="stylesheet" type="text/css" href="css/demo.css" />
    <link rel="stylesheet" type="text/css" href="css/style8.css" />
    <link href='http://fonts.googleapis.com/css?family=Terminal+Dosis' rel='stylesheet' type='text/css' />

  </head>
  <%#= stylesheet_link_tag 'application' %>

<body>


  <div class="container">
    <br>
    <br>
    <br>
    <h1>VAST/NVR Device Pack 資料庫 3.0></h1>
    <!--<div class="centered">-->
    <div class="content">
      <ul class="ca-menu">
        <li>
          <a href=<%= cct_vast_db_cameras_path %> >
            <div class="ca-content">
              <h2 class="ca-main">VAST</h2>
            </div>
          </a>
        </li>

        <li>
          <a href=<%= cct_nvr_db_cameras_path %> >
            <div class="ca-content">
              <h2 class="ca-main">NVR</h2>
            </div>
          </a>
        </li>

        <li>
          <a href=<%= welcome_test_index_index_path %> >
            <div class="ca-content">
              <h2 class="ca-main">TEST</h2>
            </div>
          </a>
        </li>




      </ul>
    </div>
  </div>



</body>

</html>