config/routes.rb
Rails.application.routes.draw do

  namespace :cct_vast_db do
    resources :cameras do
      collection do

        put  :create
        patch :update
        patch :update_soc

        post :import
        get  :create_database_index
        get  :show_cam_info
        get  :show_cam_info_index
        get  :show_soc_info
        get  :show_soc_info_index

        get  :new_and_update_cam_info_index
        get  :new_cam_info_index
        post  :new_cam_info_index

        patch :new_cam_info

        post :update_cam_info_index
        get  :update_cam_info_index
        patch  :update_success
        get  :update_cam_info

        post :test_update
        patch :test_update

        get  :update_cam_other_info_index
        get  :update_cam_other_info

        post :create_camera_other_info

        get  :export_csv_index

      end
    end
  end

  namespace :cct_vast_db do
    resources :camera_other_infos do
      collection do
        post :import
        get  :import_success
        get  :import_fail
      end
    end
  end

  namespace :cct_vast_db do
    resources :test_soc_cameras do
      collection do
        post :import
        get  :import_success
      end
    end
  end

  namespace :cct_vast_db do
    resources :show_cam_info_and_updates do
      collection do
        post  :import
        get   :import_success
      end
    end
  end

  namespace :cct_nvr_db do
    resources :cameras do
      collection do

        put  :create
        patch :update
        patch :update_soc

        post :import
        get  :create_database_index
        get  :show_cam_info
        get  :show_cam_info_index
        get  :show_soc_info
        get  :show_soc_info_index

        get  :new_and_update_cam_info_index
        get  :new_cam_info_index
        post  :new_cam_info_index

        patch :new_cam_info

        post :update_cam_info_index
        get  :update_cam_info_index
        patch  :update_success
        get  :update_cam_info

        post :test_update
        patch :test_update

        get  :update_cam_other_info_index
        get  :update_cam_other_info

        post :create_camera_other_info

        get  :export_csv_index

      end
    end
  end

  namespace :cct_nvr_db do
    resources :camera_other_infos do
      collection do
        post :import
        get  :import_success
        get  :import_fail
      end
    end
  end

  namespace :cct_nvr_db do
    resources :test_soc_cameras do
      collection do
        post :import
        get  :import_success
      end
    end

  end

  namespace :cct_nvr_db do
    resources :show_cam_info_and_updates do
      collection do
        post  :import
        get   :import_success
      end
    end
  end

  get 'welcome/test_index/index' => 'welcome/test_index#index'

  root to: "welcome/index#index"

end

app/models/cct_vast_db.rb
module CctVastDb
  def self.table_name_prefix
    'cct_vast_db_'
  end
end

app/controllers/cct_nvr_db/cameras_controller.rb
class CctNvrDb::CamerasController < ApplicationController

  # def  test_update
  #
  #   @cam_update_targets = Camera.where(:Model_FW_name => params[:check_box_ids_array])
  #   Camera.update_target(@cam_update_targets)
  #
  #   redirect_to update_cam_info_index_cameras_path
  #
  #   # if @cam_update_targets.update(camera_adding_params)
  #   #     redirect_to :back   # if write #show_cam_info_cameras_path >>> have issue!!!
  #   # end
  #
  # end


  def index
    @cameras = CctNvrDb::Camera.all
    # @cameras_other_info = CameraOtherInfo.all

    respond_to do |format|
      format.html
      format.csv { send_data @cameras.to_csv, filename: 'total_camera_info.csv'}
    end
  end


  def import
    # Camera.import(params[:file_cameras])
    # # flash[:success] = "import success!!!!!!!!!!!!!!!!!!!!!!!!"
    # existed_all_bool, @other_info_not_existed_array = CameraOtherInfo.check_all_other_info_model_existed
    #
    # if existed_all_bool
    #   redirect_to create_database_index_cameras_path
    # else
    #   redirect_to import_cameras_path
    # end

    # ori
    CctNvrDb::Camera.import(params[:file_cameras])
    existed_all_bool, @other_info_not_existed_array = CctNvrDb::CameraOtherInfo.check_all_other_info_model_existed
  end


  def new
    @camera = CctNvrDb::Camera.new
  end

  # issue here
  def show
    redirect_to root_path
  end


  def new
    @post = []
    2.times do
      @post << CctNvrDb::Camera.new
    end

  end


  def create
    # -----------------------------
    # test_add_array =
    #     [
    #         {
    #             :Model_FW_name => "Xa11",
    #             :Soc => "test1"
    #         },
    #         {
    #             :Model_FW_name => "ha22"
    #         },
    #         {
    #             :Model_FW_name => "ha33"
    #         }
    #     ]
    # ---------------------------------
    # test_add_array2 = :test_add_array

    # Rails.logger.debug("TEST cam add targets HASH!!: #{params[:cam_add_targets].inspect}")   # ok
    # Rails.logger.debug("TEST search soc HASH!!: #{params[:soc_option].inspect}")   # ok
    # Rails.logger.debug("TEST new cam ids str array HASH!!: #{params[:new_cam_ids_str_array].inspect}")   # ok

    # get new ids from hidden_field_tag in form
    new_cam_ids_array_str = params[:new_cam_ids_str_array]
    new_cam_ids_array = new_cam_ids_array_str.split(" ")
    # Rails.logger.debug("TEST new cam ids array from string HASH!!: #{new_cam_ids_array.inspect}")   # ok

    # get new cam record from ids
    new_cam_objs = CctNvrDb::ShowCamInfoAndUpdate.find(new_cam_ids_array)
    Rails.logger.debug("TEST new cam objs from string HASH!!: #{new_cam_objs.inspect}")   # ok

    added_soc_hash = CctNvrDb::ShowCamInfoAndUpdate.get_selected_to_add_cam_hash_array(new_cam_objs, params[:soc_option])

    if added_soc_hash == [{}]
      flash[:new_and_update_notice] = "Camera Name 重複，未新增，請確認！"
    elsif params[:soc_option] == ""
      flash[:new_and_update_notice] = "新增進DB成功，但Soc為空，請確認！"
    else
      flash[:new_and_update_notice] = "新增進DB成功！"
    end

    CctNvrDb::Camera.create(added_soc_hash)

    redirect_to new_and_update_cam_info_index_cct_nvr_db_cameras_path

    # ori
    # if test_add_array is not null (for protecting)
    # if !params[:test_add_array].nil?
    #   Camera.create(camera_create_params)
    # else
    #   redirect_to new_and_update_cam_info_index_cameras_path
    #   return
    # end
    # redirect_to new_cam_info_index_cameras_path
  end


  # update multi record by hash
  def update
    # @find_camera = Camera.find(645)
    # test_hash = {645 => {:uid_s0_frame_size => "X____update.1DD"}, 646 => {:uid_s0_mpeg4_max_frame_rate => "tete2"}}
    # Camera.update(test_hash.keys, test_hash.values)
    # the array only has one hash
    get_id_with_caminfo_hash = params[:test_hashhash][0]

    # pass value from hiden_field_tag id is string array, so we need to transfer type to int first
    get_id_key = []
    get_id_with_caminfo_hash.keys.each do |id_str|
      get_id_key.append(id_str.to_i)
    end

    # pass value from hiden_field_tag is string array, so we need to transfer type to hash first
    get_cam_value_hash_array = []
    get_id_with_caminfo_hash.values.each do |cams_info_hash_str|
      get_cam_value_hash_array.append(eval(cams_info_hash_str))
    end

    # Rails.logger.debug("TEST PARAMS HASH!!: #{get_id_with_caminfo_hash.inspect}")   # ok
    # Rails.logger.debug("TEST PARAMS HASH KEYS!!: #{get_id_key.inspect}")   # ok
    # Rails.logger.debug("TEST PARAMS HASH KEYS!!: #{get_cam_value_hash_array.inspect}")   # ok

    CctNvrDb::Camera.update(get_id_key, get_cam_value_hash_array)

    # original:
    # Camera.update(@get_id_with_caminfo_hash.keys, @get_id_with_caminfo_hash.values)

    redirect_to :back
  end


  def update_soc
    @cameras = CctNvrDb::Camera.all

    # id array is from hidden_field_array, and change string into int array
    soc_to_be_updated_id_str = params[:soc_to_be_updated_id_array]
    soc_to_be_updated_id_array = []
    soc_to_be_updated_id_temp_array = soc_to_be_updated_id_str.split(" ")
    soc_to_be_updated_id_temp_array.each do |soc_id_str|
      soc_to_be_updated_id_array.append(soc_id_str.to_i)
    end

    # Rails.logger.debug("TEST SOC ID PARAMS: #{soc_to_be_updated_id_array.inspect}")   # ok
    soc_option_str = params[:soc_to_be_updated]
    # Rails.logger.debug("TEST SOC PARAMS: #{soc_option_str.inspect}")   # ok

    cam_soc_to_updated_hash_hash = CctNvrDb::ShowCamInfoAndUpdate.get_selected_to_update_soc_hash_hash(soc_to_be_updated_id_array, soc_option_str)
    Rails.logger.debug("TEST SOC FINAL PARAMS: #{cam_soc_to_updated_hash_hash.inspect}")   # ok

    CctNvrDb::Camera.update(cam_soc_to_updated_hash_hash.keys, cam_soc_to_updated_hash_hash.values)

    redirect_to :back
  end


  def show_cam_info_index
    @cameras = CctNvrDb::Camera.all
    @model_name_array = CctNvrDb::Camera.get_model_name_array(@cameras)
    @soc_array = CctNvrDb::TestSocCamera.show_array_of_soc_option()

    # if search by soc option
    if params[:search_by_soc_option]
      @selected_keyword_models = CctNvrDb::Camera.search_by_soc(params[:search_by_soc_option])
    end

    # if search by keyword
    if params[:search_update_cam_by_keyword]
      @selected_keyword_models = CctNvrDb::Camera.search_by_keyword(params[:search_update_cam_by_keyword])
    end
  end


  def show_cam_info
    @cameras = CctNvrDb::Camera.all
    @cameras_other_info = CctNvrDb::CameraOtherInfo.all

    # if params[:model_fw_name_option]
    #   # @camera_model_fw_name = params[:model_fw_name_option]
    #
    #   @checked_model_array = Camera.find_by_Model_FW_name(params[:model_fw_name_option])
    #   @db_camera_name_obj_array = ShowCamInfoAndUpdate.get_db_camera_name_obj_array(@checked_model_array)
    # end

    if params[:search_update_cam]
      @selected_camera_model_fw_name = params[:search_update_cam]
    end

    # from check box checked value to get model array to be updated
    if params[:check_box_ids_array]
      # @checked_model_array = params[:check_box_ids_array]
      @checked_model_array = CctNvrDb::Camera.find(params[:check_box_ids_array])

      # # put Camera's selected model_fw_name into an array
      # @checked_model_name_str_array = []
      # @checked_model_array.each do |cheked_model_obj|
      #   @checked_model_name_str_array.append(cheked_model_obj["Model_FW_name"])
      # end
      #
      # # put Camera's selected id into an array
      # @checked_model_id_array = []
      # @checked_model_array.each do |cheked_model_obj|
      #   @checked_model_id_array.append(cheked_model_obj["id"])
      # end

      @db_camera_name_obj_array = CctNvrDb::ShowCamInfoAndUpdate.get_db_camera_name_obj_array(@checked_model_array)

    end

  end


  def show_soc_info_index
    @soc_array = CctNvrDb::TestSocCamera.show_array_of_soc_option()
    @test_cam_array = CctNvrDb::TestSocCamera.get_test_camera_model_array()


    # the following is processing
    if params[:search_compare_cam_by_keyword]
      @imported_keyword_models = CctNvrDb::TestSocCamera.search_by_keyword(params[:search_compare_cam_by_keyword])
    end

  end


  def show_soc_info
    # from check box checked value to get model array to be updated
    if params[:check_box_ids_array]
      # Rails.logger.debug("TESTTEST!!!: #{params[:check_box_ids_array].inspect}")   # ok
      # Rails.logger.debug("search soc string!!!: #{params[:search_soc].inspect}")   # ok

      # soc info
      @db_cameras_by_soc = CctNvrDb::Camera.search_soc(params[:search_soc])
      @soc_name_str = params[:search_soc]

      # for show soc's total info
      CctNvrDb::Camera.column_names.each do |column_name|

        if column_name == "id" || column_name == "created_at" || column_name == "updated_at"
          next
        else
          # we can use instance_variable_set to create instance_variable_set  by string name and
          # we can put function to set value of instance variable
          instance_variable_set("@db_#{column_name}", CctNvrDb::Camera.deal_supported_by_column_name(@db_cameras_by_soc, column_name))
        end

      end

      # ----------------------------------------------------------------------------------------------------------
      # camera info

      # Rails.logger.debug("TEST import soc cam!!!: #{params[:check_box_ids_array].inspect}")   # ok

      @test_selected_camera_array = CctNvrDb::TestSocCamera.find(params[:check_box_ids_array])
      @selected_indexed_hash = CctNvrDb::TestSocCamera.set_selected_compare_cam_to_hash(@test_selected_camera_array)
      # Rails.logger.debug("TEST indexed selected soc cam!!!: #{@selected_indexed_hash.inspect}")   # ok
      #
      # # for show test cam's info
      # Camera.column_names.each do |column_name|
      #
      #   if column_name == "id" || column_name == "created_at" || column_name == "updated_at"
      #     next
      #   else
      #
      #     # ori

app/controllers/cct_vast_db/camera_other_infos_controller.rb
class CctVastDb::CameraOtherInfosController < ApplicationController

  def import
    CctVastDb::CameraOtherInfo.import(params[:file_camera_others])

    existed_all_bool, @other_info_not_existed_array = CctVastDb::CameraOtherInfo.check_all_other_info_model_existed

    Rails.logger.debug("TEST existed_bool: #{existed_all_bool.inspect}")
    Rails.logger.debug("TEST not existed array: #{@other_info_not_existed_array.inspect}")

    # if not all CameraOtherInfo you import are in CameraInfo's model name, then delete!
    if !existed_all_bool
      # delete all CameraOtherInfo You import!!
      CctVastDb::CameraOtherInfo.destroy_all
      render "camera_other_infos/import_fail"
      # if all CameraOtherInfo you import are in CameraInfo's model name, then update all foreign key !!
    else
      CctVastDb::CameraOtherInfo.update_association_foreign_key

      redirect_to import_success_cct_vast_db_camera_other_infos_path, notice: "Activity Data imported!"
    end

  end


  def index
    @cameras_other_info = CctVastDb::CameraOtherInfo.all

    respond_to do |format|
      format.html
      format.csv { send_data @cameras_other_info.to_csv, filename: 'total_camera_other_info.csv'}
    end
  end


  #
  # def new
  #   @camera_other_info = CameraOtherInfo.new
  # end
  #
  #

end

app/controllers/cct_vast_db/show_cam_info_and_updates_controller.rb
class CctVastDb::ShowCamInfoAndUpdatesController < ApplicationController

  def import
    CctVastDb::ShowCamInfoAndUpdate.import(params[:file_update_cam_info])
    redirect_to import_success_cct_vast_db_camera_other_infos_path, notice: "Activity Data imported!"
  end

end

app/controllers/cct_vast_db/test_soc_cameras_controller.rb
class CctVastDb::TestSocCamerasController < ApplicationController
  def import
    CctVastDb::TestSocCamera.import(params[:file_test_soc_camera])
    redirect_to import_success_cct_vast_db_test_soc_cameras_path, notice: "Activity Data imported!"
  end

end

app/helpers/cct_nvr_db/cameras_helper.rb
module CctNvrDb::CamerasHelper
end

app/helpers/cct_vast_db/camera_other_infos_helper.rb
module CctVastDb::CameraOtherInfosHelper
end

app/helpers/cct_vast_db/cameras_helper.rb
module CctVastDb::CamerasHelper
end

app/helpers/cct_vast_db/show_cam_info_and_updates_helper.rb
module CctVastDb::ShowCamInfoAndUpdatesHelper
end

app/helpers/cct_vast_db/test_soc_cameras_helper.rb
module CctVastDb::TestSocCamerasHelper
end

app/views/cct_vast_db/cameras/create_database_index.html.erb
<h1>VAST Device Pack 資料庫 2.0<span>Serach、SOC Compare &amp; Update</span></h1>
<div class="center_item">

<ol>
  <li>上傳total_camera_info.csv</li>
  <%= form_tag import_cct_vast_db_cameras_path, multipart: true do %>
      <%= file_field_tag :file_cameras, multiple: false %>

      <%= submit_tag "Import CSV" , data: { disable_with: "Please wait.." }, class: 'normal_button',
                     data: { confirm: '將覆蓋舊有camera info，確定執行？', disable_with: "Please wait.."}%>
  <% end %>

  <br>
  <br>


  <li>上傳dp_others_info.csv</li>
  <%= form_tag import_cct_vast_db_camera_other_infos_path, multipart: true do %>
      <%= file_field_tag :file_camera_others, multiple: false %>
      <%= submit_tag "Import CSV" , data: { disable_with: "Please wait.." }, class: 'normal_button',
                     data: { confirm: '將覆蓋舊有other info，確定執行？', disable_with: "Please wait.."} %>
  <% end %>
  <!---------------->

</ol>
  </div>


<div class="round-button">
  <a href=<%= root_url %>>
    Home
    <!--<img src="/home_alt.png" alt="Home" />-->
    <%#= image_tag("home_alt.png", alt: "Home") %>
  </a>
</div>

app/views/cct_vast_db/cameras/import.html.erb
<!DOCTYPE html>
<html>
<head>

  <head>

  </head>
  <%= stylesheet_link_tag 'application' %>

</head>
<body>
<h1>VAST Device Pack 資料庫 2.0<span>Serach、SOC Compare &amp; Update</span></h1>

<div class=" middle_height">
  <div class="center_item" >

    <h1 style="bottom:50%">Import Success!!!</h1>
    <% if !@other_info_not_existed_array.empty? %>

        <b style="color: red">Warning!! The following camera other info's models are not in camera info!</b>
        <br>
        <br>
        <% @other_info_not_existed_array.each do |not_existed_camera_other_info|  %>

            <%= not_existed_camera_other_info %>,

        <% end %>

        <br>
        <br>
        <b>Please remember to import camera other info csv. later!!</b>
    <% end %>
  </div>

</div>

<div class="round-button">
  <a href=<%= create_database_index_cct_vast_db_cameras_path %>>
    Back
  </a>
</div>

</body>
</html>

app/views/cct_vast_db/cameras/index.html.erb
<!DOCTYPE html>
<html>
  <head>

    <head>
      <title>VAST Device Pack資料庫</title>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="Creative CSS3 Animation Menus" />
      <meta name="keywords" content="menu, navigation, animation, transition, transform, rotate, css3, web design, component, icon, slide" />
      <meta name="author" content="Codrops" />
      <link rel="shortcut icon" href="../favicon.ico">
      <link rel="stylesheet" type="text/css" href="css/demo.css" />
      <link rel="stylesheet" type="text/css" href="css/style8.css" />
      <link href='http://fonts.googleapis.com/css?family=Terminal+Dosis' rel='stylesheet' type='text/css' />

    </head>
    <%= stylesheet_link_tag 'application' %>

  </head>
  <body>

  <div>
    <div class="container">
      <br>
      <br>
      <br>
      <h1>VAST Device Pack 資料庫 2.0<span>Serach、SOC Compare &amp; Update</span></h1>
      <!--<div class="centered">-->
      <div class="content">
        <ul class="ca-menu">
          <li>
            <a href=<%= create_database_index_cct_vast_db_cameras_path %> >
              <span class="ca-icon" id="red_icon">S</span>
              <div class="ca-content">
                <h2 class="ca-main">建立資料庫</h2>
                <h3 class="ca-sub">建立initial資料庫(慎用)</h3>
              </div>
            </a>
          </li>
          <li>
            <a href=<%= show_cam_info_index_cct_vast_db_cameras_path(@cameras) %>>
              <span class="ca-icon">F</span>
              <div class="ca-content">
                <h2 class="ca-main">顯示資料庫</h2>
                <h3 class="ca-sub">顯示資料庫中model內容</h3>
              </div>
            </a>
          </li>
          <li>
            <a href=<%= show_soc_info_index_cct_vast_db_cameras_path %>>
              <span class="ca-icon" >J</span>
              <div class="ca-content">
                <h2 class="ca-main">SOC平台比對</h2>
                <h3 class="ca-sub">比對Soc與Camera</h3>
              </div>
            </a>
          </li>
          <li>
            <!--<a href=<%#= update_cam_info_index_cameras_path  %>>-->

            <a href=<%= new_and_update_cam_info_index_cct_vast_db_cameras_path  %>>

              <span class="ca-icon">L</span>
              <div class="ca-content">
                <h2 class="ca-main">新增、更新Camera/新增Other Info</h2>
                <h3 class="ca-sub">camera及版本等資訊</h3>
              </div>
            </a>
          </li>

          <li>
            <a href=<%= export_csv_index_cct_vast_db_cameras_path %>>
              <span class="ca-icon">A</span>
              <div class="ca-content">
                <h2 class="ca-main">備份資料庫</h2>
                <h3 class="ca-sub">輸出至csv檔以備份資料庫</h3>
              </div>
            </a>
          </li>
        </ul>
      </div>
      <!--</div>-->

    </div>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>

  </div>



  </body>
</html>

app/views/cct_vast_db/cameras/new.html.erb
<%= form_for @camera, :url => { :controller => 'cameras', :action => 'create' } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Create" %>
<% end %>

app/views/cct_vast_db/cameras/new_and_update_cam_info_index.html.erb
<!DOCTYPE html>
<html>
<head>

  <head>
    <!--<meta http-equiv="refresh" content="1" >-->
    <script src="sorttable.js"></script>

  </head>
  <%= stylesheet_link_tag 'application' %>

</head>
<body>
<h1>VAST Device Pack 資料庫 2.0<span>Serach、SOC Compare &amp; Update</span></h1>

<div class="center_item">

  <div class="notice_item">
    <%= flash[:new_and_update_notice] %>
  </div>


  <h1>New & Update for Camera Info </h1>

  <!--import CSV-->
  <ol>
    <li>
      <em style="color: mediumblue">Step1.</em> Select csv File to New or Update DB.(through nvr transfer tool)
    </li>
    <br>
      <%= form_tag import_cct_vast_db_show_cam_info_and_updates_path, multipart: true do %>
          <%= file_field_tag :file_update_cam_info, multiple: false %>
          <%= submit_tag "Import CSV", class:'normal_button', data: { disable_with: "Please wait.." }%>
      <% end %>

    <br>

    <% if @import_update_cameras %>
        <em>Note.</em> You can check model names you imported here.
        <br>
        <br>

        <p>The Cameras you import are:<span class="tab"></span>
          <%= select_tag :model_fw_name_option, options_for_select(@new_import_model_name_array.sort!) %>


        <!--<b>The Cameras you import are:</b>-->
        <!---->
        <!--<%# @import_update_cameras.each do |to_update_camera| %>-->
            <%#= to_update_camera["CameraModel"] %>
        <!--<%# end %>-->

        <br>
        <br>
    <% end %>
    <!--:search_by_keyword-->
    <li>
      <em style="color: mediumblue">Step2.</em> New or Update DB
    </li>
    <br>

    <%= button_to "新增", new_cam_info_index_cct_vast_db_cameras_path, class: 'normal_button' %>

    <%= button_to "更新", update_cam_info_index_cct_vast_db_cameras_path, class: 'normal_button' %>

    <br>

    <li>

      <em style="color: mediumblue">Step3.</em> New Camera Other Info
      <%= button_to "新增Other Info", update_cam_other_info_index_cct_vast_db_cameras_path, :method => 'get',
                    class: 'normal_button' %>

      <!--<a href=<%= update_cam_other_info_index_cct_vast_db_cameras_path %>>-->

          <!--</a>-->

    </li>



    <!--<a href="<%#= new_cam_info_index_cameras_path %>">新增!!</a>-->


  </ol>




</div>

<div class="round-button">
  <a href=<%= root_url %>>
    Home
  </a>
</div>


</body>
</html>

app/views/cct_vast_db/cameras/new_cam_info_index.erb
<!DOCTYPE html>
<html>
<head>

  <head>
    <!--<meta http-equiv="refresh" content="1" >-->
    <script src="sorttable.js"></script>

  </head>
  <%= stylesheet_link_tag 'application' %>

</head>
<body>
<h1>VAST Device Pack 資料庫 2.0<span>Serach、SOC Compare &amp; Update</span></h1>

  <!--recording time when enter this page-->
  <% start_new_cam_info_index_time = Time.now %>


  <div class="center_item">

    <% if @import_update_cameras %>

        <em>Note.</em> You can check model names you import here.
        <br>
        <br>

        <b>The Camera you import are:</b>
        <%= select_tag :model_name_list, options_for_select(@new_import_model_name_array.sort!) %>


    <% end %>
    <br><br>

  <ol>

    <!--by option-->
    <!--<%#= form_tag update_cam_info_cameras_path, :method => 'get' do %>-->
        <!--&lt;!&ndash;select SOC&ndash;&gt;-->
        <!--<li>-->
          <!--<p>Database Camera:<span class="tab"></span>-->
            <!--<%#= select_tag :search_update_cam, options_for_select(@update_cam_array) %>-->
            <!--<%#= submit_tag "Search", data: { disable_with: "Please wait.." }, :name => nil %>-->
          <!--</p>-->
        <!--</li>-->
        <!--<br>-->
    <!--<#% end %>-->


    <!--by keyword-->
    <%= form_tag new_cam_info_index_cct_vast_db_cameras_path, :method => 'get' do %>
        <!--select SOC-->
        <li>
          <p>Search from CSV Import:<span class="tab"></span>
            <%= text_field_tag :search_update_cam_by_keyword, params[:search_update_cam_by_keyword] %>
            <%= submit_tag "Search", class:'normal_button', data: { disable_with: "Please wait.." }, :name => nil %>
          </p>
        </li>
        <br>
    <% end %>

  </ol>


  <!--Test Show Keyword Search Result-->
  <%# if @selected_keyword_models %>
  <% if @imported_keyword_models %>

    ----------------------------------------------------------------------------------------------------
    <br>
    <em style="color: mediumblue">Search Results:</em>
    <br>

    <!--<table class="sortable" width="400">-->
    <div id="tableContainer" class="tableContainer">

      <table border="0" cellpadding="0" cellspacing="0" width="100%" class="scrollTable">
        <thead class="fixedHeader">
          <tr>
            <th>Model</th>
            <th>SOC</th>
            <th>Checkbox</th>
          </tr>
        </thead>

        <tbody class="scrollContent">
          <%= form_tag new_cam_info_cct_vast_db_cameras_path, :method => 'patch' do %>
              <%= hidden_field_tag :start_new_cam_info_index_time, start_new_cam_info_index_time %>

              <% @imported_keyword_models.each do |camera| %>
                  <% model_fw_name_str = camera["CameraModel"] %>
                  <tr>
                    <td><%= model_fw_name_str %></td>
                    <td><%= camera["Soc"] %></td>
                    <!--check_box_ids_array[] is to get model_name array you check-->
                    <td><%= check_box_tag 'check_box_ids_array[]' , camera.id %></td>
                  </tr>
              <% end %>

              <tr>
                <td>
                  <%= submit_tag "Next", class:'normal_button', data: { disable_with: "Please wait.." }, :name => nil %>
                </td>
              </tr>
          <% end %>
        </tbody>

      </table>

    </div>



    <% end %>

  </div>

  <div class="round-button">
    <a href=<%= new_and_update_cam_info_index_cct_vast_db_cameras_path %>>
      Back
    </a>
  </div>

</body>
</html>